name: CI
on:
  pull_request:
  push:
    branches: [master]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v3 # immutable tag
        with:
          cache: true
          runtime: node@latest

      # TODO: the rest
